### ISSUE TITLE
getFcsFile returns all files instead of individual file

### ISSUE THREAD

**Issue by pfgherardini** [primitybio/cellengine-r-toolkit#11]
This function should return an individual file according to the description, instead all of them are returned

**Comment by zbjornson** [comment]
Are you using a query, or just the `experimentId` and `fcsFileId`?

**Comment by pfgherardini** [comment]
I am doing

```
res <- getFcsFile(experimentId, fileId)
```

and now res contains all the files, instead of just the one corresponding to fileId

**Comment by zbjornson** [comment]
I'm not seeing any requests in our logs that would correspond with that function call -- can you triple check that `fileId` is defined please? (We should add a line to the function to check that fileId is defined before sending out the request in any case.)

**Comment by pfgherardini** [comment]
My bad! It was undefined... yes maybe a good idea to add some chekcing in the function

**Comment by pfgherardini** [comment]
I should say though that, on second thought, that function is not particularly useful, since you have to call getFcsFiles first anyways in order to know the id of the file
