### ISSUE TITLE
Export lookupByName helper function(s)

### ISSUE THREAD

**Issue by zbjornson** [primitybio/cellengine-r-toolkit#31]
Request from Federico.

Our internal `lookupByName` function won't work out of the box because it takes an API URL as the first argument; need specializations for each resource type. Some ideas:

```R
lookupByName("gate", "my gate's name")
lookupGateByName("my gate's name")
lookup("gate", list(name = "my gate's name")) # generic lookup fn, probably too verbose
```

**Comment by gegnew** [comment]
There's kind of two options here:
1) export a specific implementation of the current `lookupByName` function that accepts a name and turns it into a an API URL
2) modify the current `lookupByName` function to accept a URL _or_ an identifier, then export the current function

I like 2,  except that it's blocked by the `_boxed_by_name` class; the current internal function only looks up a name that  has been passed by a user with `byName()`. We could remove `byName` and just allow a name or an `_id` as an arg to `lookupByName`

What are your thoughts?

**Comment by gegnew** [comment]
completed
