### ISSUE TITLE
Add event number to TSV returned by getEvents

### ISSUE THREAD

**Issue by cphealy8** [primitybio/cellengine-r-toolkit#92]
This would be very helpful for comparing events before and after post-processing.

**Comment by zbjornson** [comment]
Sorry for the delay. This is now implemented in both `master` and `v1-dev` branches. If you're not already doing so, I highly recommend using the v1-dev branch. There's a list of changes here: https://github.com/primitybio/cellengine-r-toolkit/blob/v1-dev/CHANGELOG.md. I think we're done with most of the breaking changes.
